package isaps.tim18.PSW_ISA_ClinicalC_2019.selenium;// Generated by Selenium IDE
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;
public class ZahteviAdminTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/resources/chromedriver.exe");
    driver = new ChromeDriver();
    driver.get("http://localhost:4200");
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void zahteviAdmin() {
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".img-fluid")));
    }
    driver.findElement(By.linkText("Prijava")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("email")));
    }
    driver.findElement(By.id("email")).sendKeys("anamarija@mailsac.com");
    driver.findElement(By.id("lozinka")).sendKeys("12345678b");
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".third")));
    }
    driver.findElement(By.cssSelector(".third")).click();
    driver.findElement(By.linkText("Zahtevi za preglede/operacije")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("#\\31 > .mat-button-wrapper")));
    }
    driver.findElement(By.cssSelector("#\\31 > .mat-button-wrapper")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("mat-input-1")));
    }
    driver.findElement(By.id("mat-input-1")).sendKeys("1A");
    driver.findElement(By.id("mat-input-1")).sendKeys("Mala sala");
    driver.findElement(By.cssSelector(".cdk-column-Kalendar > #\\32 > .mat-button-wrapper")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".e-appointment:nth-child(1) .e-subject")));
    }
    driver.findElement(By.cssSelector(".e-appointment:nth-child(1) .e-subject")).click();
    driver.findElement(By.cssSelector(".e-close")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.cssSelector(".cdk-column-ZakaziTermin > #\\32 > .mat-button-wrapper")).click();
    driver.findElement(By.cssSelector(".mat-select-arrow-wrapper")).click();
    driver.findElement(By.cssSelector(".mat-option-text")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".cdk-focused > .mat-button-wrapper")));
    }
    driver.findElement(By.cssSelector(".cdk-focused > .mat-button-wrapper")).click();
  }
}
