insert into lekar (id, grad, drzava, adresa, jbo, aktivnost_naloga, email, ime, kontakt_telefon, kor_ime, lozinka, prezime, br_slobodnih_dana, tip_korisnika) values (1, 'Backa Palanka', 'Srbija', 'Save Kovacevica 47', 123456789, True, 'ivanabrkic192@gmail.com', 'Ivana', '0652754579', 'ika', '12345678', 'Brkic', 65, 'Lekar');
insert into lekar (id, grad, drzava, adresa, jbo, aktivnost_naloga, email, ime, kontakt_telefon, kor_ime, lozinka, prezime, br_slobodnih_dana, tip_korisnika) values (2, 'Indjija', 'Srbija', 'Glavna 38', 987654321, True,'vladimirpopovic@gmail.com', 'Vladimir', '0652754579', 'vlada', '12345678', 'Popovic', 23, 'Lekar');
insert into lekar (id, grad, drzava, adresa, jbo, aktivnost_naloga, email, ime, kontakt_telefon, kor_ime, lozinka, prezime, br_slobodnih_dana, tip_korisnika) values (3, 'Sabac', 'Srbija', 'Mladena Djuricica 11', 123123123, True, 'tamaralazarevic@gmail.com', 'Tamara', '0652754579', 'tesla', '12345678', 'Lazarevic', 11, 'Lekar');


insert into administrator_klinike (id, grad, drzava, adresa, jbo, aktivnost_naloga, email, ime, kontakt_telefon, kor_ime, lozinka, prezime, tip_korisnika) values (4, 'Novi Sad', 'Srbija', 'Mise Dimitrijevica 51', 123321123, True, 'anamarija@gmail.com', 'Ana-Marija', '0652754579', 'anacrtica', '12345678', 'Buhmiler', 'Administrator klinike');
insert into administrator_klinike (id, grad, drzava, adresa, jbo, aktivnost_naloga, email, ime, kontakt_telefon, kor_ime, lozinka, prezime, tip_korisnika) values (5, 'Nova Pazova', 'Srbija', 'Vojvode Misica 30', 654123654, True,'nikolamilosevic@gmail.com', 'Nikola', '0652754579', 'vanelee', '12345678', 'Milosevic', 'Administrator klinike');

insert into administrator_klinickog_centra (id, grad, drzava, adresa, jbo, aktivnost_naloga, email, ime, kontakt_telefon, kor_ime, lozinka, prezime, tip_korisnika) values (1, 'Backa Palanka', 'Srbija', 'Save Kovacevica 47', 123456789, True, 'ivanabrkic192@gmail.com', 'Ivana', '0652754579', 'ika', '12345678', 'Brkic', 'Administrator klinickog centra');

insert into pacijent (id, grad, drzava, adresa, jbo, aktivnost_naloga, email, ime, kontakt_telefon, kor_ime, lozinka, prezime, tip_korisnika) values (6, 'Beocin', 'Srbija', 'Zlatiborska 40', 876656654, True,'milanlux@gmail.com', 'Milan', '0652754579', 'lux', '12345678', 'Lukovic', 'Pacijent');
insert into pacijent (id, grad, drzava, adresa, jbo, aktivnost_naloga, email, ime, kontakt_telefon, kor_ime, lozinka, prezime, tip_korisnika) values (7, 'Brazilija', 'Srbija', 'Tarska 40', 342378491, True, 'milanlukic@gmail.com', 'Milance', '0652754579', 'mix', '12345678', 'Lukic', 'Pacijent');

insert into medicinska_sestra (id, grad, drzava, adresa, jbo, aktivnost_naloga, email, ime, kontakt_telefon, kor_ime, lozinka, prezime, br_slobodnih_dana, tip_korisnika) values (8, 'Backa Palanka', 'Srbija', 'Save Kovacevica 50', 645238967, True, 'ivanabrkic192@gmail.com', 'Ivanica', '0652754579', 'maxiixa', '12345678', 'Maksimovica', 65, 'Medicinska sestra');
insert into medicinska_sestra (id, grad, drzava, adresa, jbo, aktivnost_naloga, email, ime, kontakt_telefon, kor_ime, lozinka, prezime, br_slobodnih_dana, tip_korisnika) values (9, 'Indjija', 'Srbija', 'Glavna 38', 645987234, True,'vladimirpopovic@gmail.com', 'Vladimirko', '0652754579', 'popvlada', '12345678', 'Popov', 23, 'Medicinska sestra');
